config/routes.rb
BestFacts::Application.routes.draw do

   root 'fact#home'
   get "edit/:id" => "fact#edit", :as => :edit
   post "update/:id" => "fact#update", :as => :update
   get "delete/:id" => "fact#delete", :as => :delete
   get "home" => "fact#home"
   post 'fact/create' => 'fact#create', :as =>:create
   get 'fact/demo' => 'fact#demo'
   get 'fact/home' => 'fact#home'

end

app/models/fact.rb
class Fact < ActiveRecord::Base
  
   has_attached_file :fact_image, :styles => { :medium => "300x300>", :thumb => "100x100>", :small => "411x274>", :large => "1280x854>" }, :default_url => "/images/missing.gif"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with:  :exception
end

app/controllers/fact_controller.rb
class FactController < ApplicationController
  def home
    @fact = Fact.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
    @facts = Fact.new
    respond_to do |format|
      format.json {render :json => @fact}
      format.xml {render :xml => @fact}
      
   # render :layout => "home"
  end
  end

  def demo
    render :layout => "home"
  end

  def create
  @fact = Fact.create(fact_params)
    if @fact.save
      redirect_to root_url
    else
      render root_url
    end
  end

  def edit
    @edit = Fact.find_by_id(params[:id])
    render :layout => "home"
  end

  def update
    @update = Fact.find_by_id(params[:id])
    @update.update_attributes(fact_params)
    if @update.save
      redirect_to root_url
    else
      render "edit"
    end
   
  end

  def delete
    @delete = Fact.find_by_id(params[:id])
    if @delete.destroy
      redirect_to root_url
    else
      render "home"
    end
  end

  private

  def fact_params
    params.require(:fact).permit(:id ,:title, :content, :author,:fact_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fact_helper.rb
module FactHelper
end

app/views/fact/edit.html.erb
<h1>Edit Fact</h1>


<%= form_for @edit, :as => :fact , :url => update_path,:id => @edit.id,:html => {:class => "input_field_div",:multipart => true }, :method => "post" do |f| %>

<div class="field_hight">
  <label>Title</label><br/>
<%= f.text_field :title, :class => "text_field_div" %>
</div>

  <div class="field_hight">
  <label>Author</label><br/>
  <%= f.file_field :fact_image, :class => "text_field_div" %>
</div>


<div class="field_hight">
  <label>Author</label><br/>
  <%= f.text_field :author, :class => "text_field_div" %>
</div>

   <div class="field_hight">
  <label>Content</label><br/>
  <%= f.text_area :content,:class => "text_area_div" %>

</div>


<div class="submit_button">
  <%= f.submit "Submit" , :class => "submit_button_tec"%>
</div>





<% end %>

app/views/fact/home.html.erb
<script type="text/javascript">
function change_rest_type(id){

var children_ids = [];


$("div.top").contents().filter(

  function(){
    if (this.nodeType == 1) { // nodeType 1 => div
      // reg exp matches div
        try {
          children_ids.push(this.id);
        } catch(e){}
    }
  }
);

// or maybe the more familiar, the non-jquery way
for(var i = 0 ; i < children_ids.length; i++){
 $("#"+children_ids[i]).hide();
}
$("#"+id).show();

}
</script>
<script type="text/javascript">
 

  function confirmDeleteValidate(){
var Check = confirm("You Want to delete this Fact");
if(Check){
    return true;
}else{
    return false;
}

}

</script>





<div id="wrapper">


  <div class="actions" ><span class="bus_back"><a href="javascript:void(0)" onclick="change_rest_type('add_wish')" style="font-size: 16px;
color: gray;"> Add Fact</a></span></div>
 <div id="add_wish" style="display: none;">


<%= form_for @facts, :as => :fact , :url => create_path,:html => {:class => "input_field_div",:multipart => true } , :method => "post" do |f| %>

<div class="field_hight">
  <label>Title</label><br/>
<%= f.text_field :title, :class => "text_field_div" %>
</div>




<div class="field_hight">
  <label>Author</label><br/>
  <%= f.text_field :author, :class => "text_field_div" %>
</div>

   <div class="field_hight">
  <label>Author</label><br/>
  <%= f.file_field :fact_image, :class => "text_field_div" %>
</div>

   <div class="field_hight">
  <label>Content</label><br/>
  <%= f.text_area :content,:class => "text_area_div" %>

</div>


<div class="submit_button">
  <%= f.submit "Submit" , :class => "submit_button_tec"%>
</div>






<% end %>

 </div>

  <h1 style="font-size:18px;">List of Facts</h1>
 
<table id="keywords" cellspacing="0" cellpadding="0" class="table_field">
        <thead>
          <tr align="center" class="serial" >
            <th class="headerheaderSortDown"><span>Sr No.</span></th>
            <th><span>Fact Image</span></th>
            <th><span>Title</span></th>
            
            <th><span>Content</span></th>
            <th><span>Author</span></th>

                            <th>Actions</th>

                        </tr>


                    </thead>
                    <tbody>
<%@count=0%>

                      <% @fact.each do |fact|  %>
                      <tr class="alt" align="center">
                              <td><%=@count+= 1  %></td>
                              <td><%= image_tag fact.fact_image.url(:thumb) ,:size => "50x50"%></td>
                                  <td><%=fact.title%></td>
                                  
                        <td ><%=fact.content%></td>
                        <td ><%=fact.author%></td>
                        
                        <td ><%= link_to 'Edit', edit_path(fact.id) %>/<%= link_to 'Delete', delete_path(fact.id),:onclick=>" return confirmDeleteValidate();" %></td>
                                    </tr>
                               <%end%>

                        </tbody>
                </table>
<%= will_paginate @fact %>
</div>
<script type="text/javascript">
$(function(){
  $('#keywords').tablesorter();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BestFacts</title>
 <link rel="shortcut icon" href="http://d15dxvojnvxp1x.cloudfront.net/assets/favicon.ico">
  <link rel="icon" href="http://d15dxvojnvxp1x.cloudfront.net/assets/favicon.ico">
  <link rel="stylesheet" type="text/css" media="all" href="public/css/styles.css">
  <script type="text/javascript" src="public/js/jquery-1.10.2.min.js"></script>
  <script type="text/javascript" src="public/js/jquery.tablesorter.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
   
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>BestFact</title>

<%= stylesheet_link_tag    "styles", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag    "sort", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery-1.10.2.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "sort", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.tablesorter.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery-1.8.3.min.js", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.elevatezoom.js", "data-turbolinks-track" => true %>


<link rel="icon" href="public/images/icon.ico" />
</head>

<body>
<%=yield%>
</body>
</html>